/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const START_USER_TOUR = "START_USER_TOUR";
export const STOP_USER_TOUR = "STOP_USER_TOUR";
export const TOGGLE_DARK_SIDENAV = "TOGGLE_DARK_SIDENAV";
export const GET_MEDIA_SOURCE_START = "GET_MEDIA_SOURCE_START";
export const GET_MEDIA_SOURCE_FINISH = "GET_MEDIA_SOURCE_FINISH";

// Chat App Actions
export const CHAT_WITH_SELECTED_USER = "CHAT_WITH_SELECTED_USER";
export const SEND_MESSAGE_TO_USER = "SEND_MESSAGE_TO_USER";
export const UPDATE_USERS_SEARCH = "UPDATE_USERS_SEARCH";
export const SEARCH_USERS = "SEARCH_USERS";
export const GET_RECENT_CHAT_USERS = "GET_RECENT_CHAT_USERS";

// Mail App
export const GET_EMAILS = "GET_EMAILS";
export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS";
export const GET_EMAIL_FAILURE = "GET_EMAIL_FAILURE";
export const SET_EMAIL_AS_STAR = "SET_EMAIL_AS_STAR";
export const READ_EMAIL = "READ_EMAIL";
export const HIDE_LOADING_INDICATOR = "HIDE_LOADING_INDICATOR";
export const FETCH_EMAILS = "FETCH_EMAILS";
export const ON_SELECT_EMAIL = "ON_SELECT_EMAIL";
export const UPDATE_EMAIL_SEARCH = "UPDATE_EMAIL_SEARCH";
export const SEARCH_EMAIL = "SEARCH_EMAIL";
export const ON_DELETE_MAIL = "ON_DELETE_MAIL";
export const ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING =
  "ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING";
export const GET_SENT_EMAILS = "GET_SENT_EMAILS";
export const GET_INBOX = "GET_INBOX";
export const GET_DRAFTS_EMAILS = "GET_DRAFTS_EMAILS";
export const GET_SPAM_EMAILS = "GET_SPAM_EMAILS";
export const GET_TRASH_EMAILS = "GET_TRASH_EMAILS";
export const ON_EMAIL_MOVE_TO_FOLDER = "ON_EMAIL_MOVE_TO_FOLDER";
export const SELECT_ALL_EMAILS = "SELECT_ALL_EMAILS";
export const UNSELECT_ALL_EMAILS = "UNSELECT_ALL_EMAILS";
export const ON_SEND_EMAIL = "ON_SEND_EMAIL";
export const EMAIL_SENT_SUCCESSFULLY = "EMAIL_SENT_SUCCESSFULLY";
export const FILTER_EMAILS_WITH_LABELS = "FILTER_EMAILS_WITH_LABELS";
export const ADD_LABELS_INTO_EMAILS = "ADD_LABELS_INTO_EMAILS";

// Sidebar
export const TOGGLE_MENU = "TOGGLE_MENU";

// Agency Sidebar
export const AGENCY_TOGGLE_MENU = "AGENCY_TOGGLE_MENU";
export const CHANGE_AGENCY_LAYOUT_BG = "CHANGE_AGENCY_LAYOUT_BG";

//Master Panel Sidebar
export const TOGGLE_MASTER_PANEL_MENU = "TOGGLE_MASTER_PANEL_MENU";
//export const CHANGE_AGENCY_LAYOUT_BG = 'CHANGE_AGENCY_LAYOUT_BG';

// ToDo App
export const GET_TODOS = "GET_TODOS";
export const FETCH_TODOS = "FETCH_TODOS";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const ON_SELECT_TODO = "ON_SELECT_TODO";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";
export const ON_BACK_TO_TODOS = "ON_BACK_TO_TODOS";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const MARK_AS_STAR_TODO = "MARK_AS_STAR_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const ADD_LABELS_INTO_THE_TASK = "ADD_LABELS_INTO_THE_TASK";
export const GET_ALL_TODO = "GET_ALL_TODO";
export const GET_COMPLETED_TODOS = "GET_COMPLETED_TODOS";
export const GET_DELETED_TODOS = "GET_DELETED_TODOS";
export const GET_STARRED_TODOS = "GET_STARRED_TODOS";
export const GET_FILTER_TODOS = "GET_FILTER_TODOS";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const UPDATE_TASK_TITLE = "UPDATE_TASK_TITLE";
export const UPDATE_TASK_DESCRIPTION = "UPDATE_TASK_DESCRIPTION";
export const CHANGE_TASK_ASSIGNER = "CHANGE_TASK_ASSIGNER";
export const ON_CHECK_BOX_TOGGLE_TODO_ITEM = "ON_CHECK_BOX_TOGGLE_TODO_ITEM";
export const SELECT_ALL_TODO = "SELECT_ALL_TODO";
export const GET_UNSELECTED_ALL_TODO = "GET_UNSELECTED_ALL_TODO";
export const SELECT_STARRED_TODO = "SELECT_STARRED_TODO";
export const SELECT_UNSTARRED_TODO = "SELECT_UNSTARRED_TODO";
export const ON_LABEL_SELECT = "ON_LABEL_SELECT";
export const ON_LABEL_MENU_ITEM_SELECT = "ON_LABEL_MENU_ITEM_SELECT";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const SEARCH_TODO = "SEARCH_TODO";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

// Auth Actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
export const LOGIN_FACEBOOK_USER = "LOGIN_FACEBOOK_USER";
export const LOGIN_GOOGLE_USER = "LOGIN_GOOGLE_USER";
export const LOGIN_TWITTER_USER = "LOGIN_TWITTER_USER";
export const LOGIN_GITHUB_USER = "LOGIN_GITHUB_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export const CREATE_TWO_STEP_TOKEN_START = "CREATE_TWO_STEP_TOKEN_START";
export const CREATE_TWO_STEP_TOKEN_FINISH = "CREATE_TWO_STEP_TOKEN_FINISH";

// Feedbacks
export const GET_FEEDBACKS = "GET_FEEDBACKS";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";
export const GET_FEEDBACKS_FAILURE = "GET_FEEDBACKS_FAILURE";
export const GET_ALL_FEEDBACKS = "GET_ALL_FEEDBACKS";
export const ON_CHANGE_FEEDBACK_PAGE_TABS = "ON_CHANGE_FEEDBACK_PAGE_TABS";
export const MAKE_FAVORITE_FEEDBACK = "MAKE_FAVORITE_FEEDBACK";
export const ON_DELETE_FEEDBACK = "ON_DELETE_FEEDBACK";
export const VIEW_FEEDBACK_DETAILS = "VIEW_FEEDBACK_DETAILS";
export const ADD_NEW_FEEDBACK = "ADD_NEW_FEEDBACK";
export const SHOW_FEEDBACK_LOADING_INDICATOR =
  "SHOW_FEEDBACK_LOADING_INDICATOR";
export const HIDE_FEEDBACK_LOADING_INDICATOR =
  "HIDE_FEEDBACK_LOADING_INDICATOR";
export const NAVIGATE_TO_BACK = "NAVIGATE_TO_BACK";
export const REPLY_FEEDBACK = "REPLY_FEEDBACK";
export const SEND_REPLY = "SEND_REPLY";
export const UPDATE_SEARCH_IDEA = "UPDATE_SEARCH_IDEA";
export const ON_SEARCH_IDEA = "ON_SEARCH_IDEA";
export const ON_COMMENT_FEEDBACK = "ON_COMMENT_FEEDBACK";

// ecommerce
export const ON_DELETE_ITEM_FROM_CART = "ON_DELETE_ITEM_FROM_CART";
export const ON_QUANTITY_CHANGE = "ON_QUANTITY_CHANGE";
export const ON_ADD_ITEM_TO_CART = "ON_ADD_ITEM_TO_CART";

//AUth

export const SIGNIN_USER = "SIGNIN_USER";

//user actions
export const GET_CLIENTS = "GET_CLIENS";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_FAILURE = "GET_CLIENTS_FAILURE";
export const SELECT_USER = "SELECT_USER";
export const SELECT_USER_SUCCESS = "SELECT_USER_SUCCESS";

//Client Admin actions
export const CREATE_CLIENT_ADMIN = "CREATE_CLIENT_ADMIN";
export const UPDATE_CLIENT_ADMIN = "UPDATE_USER_ADMIN";
export const LIST_CLIENT_ADMIN = "LIST_CLIENT_ADMIN";
export const DELETE_CLIENT_ADMIN = "DELETE_CLIENT_ADMIN";
export const GET_CLIENT_ADMIN = "GET_CLIENT_ADMIN";

export const GET_CLIENT_ADMIN_SUCCESS = "GET_CLIENT_ADMIN_SUCCESS";
export const GET_CLIENT_ADMIN_FAILURE = "GET_CLIENT_ADMIN_FAILURE";

export const ADD_CLIENT_ADMIN_SUCCESS = "ADD_CLIENT_ADMIN_SUCCESS";
export const ADD_CLIENT_ADMIN_FAILURE = "ADD_CLIENT_ADMIN_FAILURE";

export const DELETE_CLIENT_ADMIN_SUCCESS = "DELETE_CLIENT_ADMIN_SUCCESS";
export const DELETE_CLIENT_ADMIN_FAILURE = "DELETE_CLIENT_ADMIN_FAILURE";

export const UPDATE_CLIENT_ADMIN_SUCCESS = "UPDATE_CLIENT_ADMIN_SUCCESS";
export const UPDATE_CLIENT_ADMIN_FAILURE = "UPDATE_CLIENT_ADMIN_FAILURE";

export const LIST_CLIENT_ADMIN_SUCCESS = "LIST_CLIENT_ADMIN_SUCCESS";
export const LIST_CLIENT_ADMIN_FAILURE = "LIST_CLIENT_ADMIN_FAILURE";

//Octoadmin actions

export const CREATE_OCTO_ADMIN = "CREATE_OCTO_ADMIN";
export const UPDATE_OCTO_ADMIN = "UPDATE_OCTO_ADMIN";
export const LIST_OCTO_ADMIN = "LIST_OCTO_ADMIN";
export const DELETE_OCTO_ADMIN = "DELETE_OCTO_ADMIN";
export const GET_OCTO_ADMIN = "GET_OCTO_ADMIN";

export const GET_OCTO_ADMIN_SUCCESS = "GET_OCTO_ADMIN_SUCCESS";
export const GET_OCTO_ADMIN_FAILURE = "GET_OCTO_ADMIN_FAILURE";

export const ADD_OCTO_ADMIN_SUCCESS = "ADD_OCTO_ADMIN_SUCCESS";
export const ADD_OCTO_ADMIN_FAILURE = "ADD_OCTO_ADMIN_FAILURE";

export const DELETE_OCTO_ADMIN_SUCCESS = "DELETE_OCTO_ADMIN_SUCCESS";
export const DELETE_OCTO_ADMIN_FAILURE = "DELETE_OCTO_ADMIN_FAILURE";

export const UPDATE_OCTO_ADMIN_SUCCESS = "UPDATE_OCTO_ADMIN_SUCCESS";
export const UPDATE_OCTO_ADMIN_FAILURE = "UPDATE_OCTO_ADMIN_FAILURE";

export const LIST_OCTO_ADMIN_SUCCESS = "LIST_OCTO_ADMIN_SUCCESS";
export const LIST_OCTO_ADMIN_FAILURE = "LIST_OCTO_ADMIN_FAILURE";

export const ASSIGN_OCTO_ADMIN_START = "ASSIGN_OCTO_ADMIN_START";
export const ASSIGN_OCTO_ADMIN_FINISH = "ASSIGN_OCTO_ADMIN_FINISH";

//user client actions

export const CREATE_CLIENT_USER = "CREATE_CLIENT_USER";
export const UPDATE_CLIENT_USER = "UPDATE_USER_USER";
export const LIST_CLIENT_USERS = "LIST_CLIENT_USERS";
export const DELETE_CLIENT_USER = "DELETE_CLIENT_USER";
export const GET_CLIENT_USER = "GET_CLIENT_USER";

export const GET_CLIENT_USER_SUCCESS = "GET_CLIENT_USER_SUCCESS";
export const GET_CLIENT_USER_FAILURE = "GET_CLIENT_USER_FAILURE";

export const ADD_CLIENT_USER_SUCCESS = "ADD_CLIENT_USER_SUCCESS";
export const ADD_CLIENT_USER_FAILURE = "ADD_CLIENT_USER_FAILURE";

export const DELETE_CLIENT_USER_SUCCESS = "DELETE_CLIENT_USER_SUCCESS";
export const DELETE_CLIENT_USER_FAILURE = "DELETE_CLIENT_USER_FAILURE";

export const UPDATE_CLIENT_USER_SUCCESS = "UPDATE_CLIENT_USER_SUCCESS";
export const UPDATE_CLIENT_USER_FAILURE = "UPDATE_CLIENT_USER_FAILURE";

export const LIST_CLIENT_USERS_SUCCESS = "LIST_CLIENT_USERS_SUCCESS";
export const LIST_CLIENT_USERS_FAILURE = "LIST_CLIENT_USERS_FAILURE";

export const DEACTIVATE_CLIENT_USER_FINISH = "DEACTIVATE_CLIENT_USER_FINISH";
export const DEACTIVATE_CLIENT_USER_START = "DEACTIVATE_CLIENT_USER_START";

//handles actions

export const DELETE_SCREEN_START = "DELETE_SCREEN_START";
export const DELETE_SCREEN_FINISH = "DELETE_SCREEN_FINISH";
export const CREATE_HANDLE_START = "CREATE_HANDLE_START";
export const UPDATE_HANDLE_START = "UPDATE_HANDLE_START";
export const LIST_HANDLES_START = "LIST_HANDLES_START";
export const DELETE_HANDLE_START = "DELETE_HANDLE_START";

export const CREATE_HANDLE_FINISH = "CREATE_HANDLE_FINISH";
export const DELETE_HANDLE_FINISH = "DELETE_HANDLE_FINISH";
export const UPDATE_HANDLE_FINISH = "UPDATE_HANDLE_FINISH";
export const LIST_HANDLES_FINISH = "LIST_HANDLES_FINISH";

//NEWS SOURCE actions

export const CREATE_NEWS_SOURCE_START = "CREATE_NEWS_SOURCE_START";
export const UPDATE_NEWS_SOURCE_START = "UPDATE_NEWS_SOURCE_START";
export const LIST_NEWS_SOURCES_START = "LIST_NEWS_SOURCES_START";
export const DELETE_NEWS_SOURCE_START = "DELETE_NEWS_SOURCE_START";

export const CREATE_NEWS_SOURCE_FINISH = "CREATE_NEWS_SOURCE_FINISH";
export const DELETE_NEWS_SOURCE_FINISH = "DELETE_NEWS_SOURCE_FINISH";
export const UPDATE_NEWS_SOURCE_FINISH = "UPDATE_NEWS_SOURCE_FINISH";
export const LIST_NEWS_SOURCES_FINISH = "LIST_NEWS_SOURCES_FINISH";

//Topic actions

export const CREATE_TOPIC_START = "CREATE_TOPIC_START";
export const UPDATE_TOPIC_START = "UPDATE_TOPIC_START";
export const LIST_TOPICS_START = "LIST_TOPICS_START";
export const DELETE_TOPIC_START = "DELETE_TOPIC_START";

export const CREATE_TOPIC_FINISH = "CREATE_TOPIC_FINISH";
export const DELETE_TOPIC_FINISH = "DELETE_TOPIC_FINISH";
export const UPDATE_TOPIC_FINISH = "UPDATE_TOPIC_FINISH";
export const LIST_TOPICS_FINISH = "LIST_TOPICS_FINISH";

//Tags actions

export const CREATE_TAG_START = "CREATE_TAG_START";
export const UPDATE_TAG_START = "UPDATE_TAG_START";
export const LIST_TAGS_START = "LIST_TAGS_START";
export const DELETE_TAG_START = "DELETE_TAG_START";

export const CREATE_TAG_FINISH = "CREATE_TAG_FINISH";
export const DELETE_TAG_FINISH = "DELETE_TAG_FINISH";
export const UPDATE_TAG_FINISH = "UPDATE_TAG_FINISH";
export const LIST_TAGS_FINISH = "LIST_TAGS_FINISH";

//Client Actions
export const GET_CLIENT_START = "GET_CLIENT_START";
export const CREATE_CLIENT_START = "CREATE_CLIENT_START";
export const UPDATE_CLIENT_START = "UPDATE_CLIENT_START";
export const LIST_CLIENTS_START = "LIST_CLIENTS_START";
export const DELETE_CLIENT_START = "DELETE_CLIENT_START";

export const GET_CLIENT_FINISH = "GET_CLIENT_FINISH";
export const CREATE_CLIENT_FINISH = "CREATE_CLIENT_FINISH";
export const UPDATE_CLIENT_FINISH = "UPDATE_CLIENT_FINISH";
export const LIST_CLIENTS_FINISH = "LIST_CLIENTS_FINISH";
export const DELETE_CLIENT_FINISH = "DELETE_CLIENT_FINISH";
export const SELECT_CLIENT_START = "SELECT_CLIENT_START";
export const SELECT_CLIENT_FINISH = "SELECT_CLIENT_FINISH";
export const GET_TOPICS_LIST = "GET_TOPICS_LIST";
export const GET_TOPICS_RESULT = "GET_TOPICS_RESULT";
export const ADD_TOPIC_START = "ADD_TOPIC_START";
export const ADD_TOPIC_RESULT = "ADD_TOPIC_RESULT";
export const UPDATE_TOPICS_START = "UPDATE_TOPICS_START";
export const UPDATE_TOPICS_RESULT = "UPDATE_TOPICS_RESULT";

//Update Permissions
export const UPDATE_PERMISSIONS_START = "UPDATE_PERMISSIONS_START";
export const UPDATE_PERMISSIONS_FINISH = "UPDATE_PERMISSIONS_FINISH";

//Package
export const GET_PACKAGE_START = "GET_PACKAGE_START";
export const GET_PACKAGE_FINISHED = "GET_PACKAGE_FINISHED";

export const LIST_PACKAGES_START = "LIST_PACKAGES_START";
export const LIST_PACKAGES_FINISHED = "LIST_PACKAGES_FINISHED";

export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_FINISH = "GET_CATEGORIES_FINISH";

export const GET_CATEGORY_START = "GET_CATEGORY_START";
export const GET_CATEGORY_FINISH = "GET_CATEGORY_FINISH";



export const EDIT_CATEGORY_LINK_START = "EDIT_CATEGORY_LINK_START";
export const EDIT_CATEGORY_LINK_FINISH = "EDIT_CATEGORY_LINK_FINISH";




export const EDIT_CATEGORY_START = "EDIT_CATEGORY_START";
export const EDIT_CATEGORY_FINISH = "EDIT_CATEGORY_FINISH";

export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_FINISH = "ADD_CATEGORY_FINISH";

export const ADD_CATEGORY_LINK_START = "ADD_CATEGORY_LINK_START";
export const ADD_CATEGORY_LINK_FINISH = "ADD_CATEGORY_LINK_FINISH";

export const DELETE_CATEGORY_LINK_START = "DELETE_CATEGORY_LINK_START";
export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_FINISH = "DELETE_CATEGORY_FINISH";
export const DELETE_CATEGORY_LINK_FINISH = "DELETE_CATEGORY_LINK_FINISH";

export const SAVE_CATEGORY_LINKS_USER_START = "SAVE_CATEGORY_LINKS_USER_START";
export const SAVE_CATEGORY_LINKS_USER_FINISH =
  "SAVE_CATEGORY_LINKS_USER_FINISH";

export const GET_CATEGORY_LINKS_USER_START = "GET_CATEGORY_LINKS_USER_START";
export const GET_CATEGORY_LINKS_USER_FINISH = "GET_CATEGORY_LINKS_USER_FINISH";

export const GET_LIVE_TWEETS_START = "GET_LIVE_TWEETS_START";
export const GET_LIVE_TWEETS_FINISH = "GET_LIVE_TWEETS_FINISH";

export const GET_AGGREGATE_COMMENTS_START = "GET_AGGREGATE_COMMENTS_START";
export const GET_AGGREGATE_COMMENTS_FINISH = "GET_AGGREGATE_COMMENTS_FINISH";

export const EDIT_YOUTUBE_SENTIMENT_START = "EDIT_YOUTUBE_SENTIMENT_START";
export const EDIT_YOUTUBE_SENTIMENT_FINISH = "EDIT_YOUTUBE_SENTIMENT_FINISH";

export const EDIT_TWITTER_SENTIMENT_START = "EDIT_TWITTER_SENTIMENT_START";
export const EDIT_TWITTER_SENTIMENT_FINISH = "EDIT_TWITTER_SENTIMENT_FINISH";

export const HIDE_CLIENT_SELECTOR = "HIDE_CLIENT_SELECTOR";
export const SHOW_CLIENT_SELECTOR = "SHOW_CLIENT_SELECTOR";

export const CHANGE_USER_PASSWORD_START = "CHANGE_USER_PASSWORD_START";
export const CHANGE_USER_PASSWORD_FINISH = "CHANGE_USER_PASSWORD_FINISH";

export const ADD_SENTIMENT_KEYWORD_START = "ADD_SENTIMENT_KEYWORD_START";
export const ADD_SENTIMENT_KEYWORD_FILE_START = "ADD_SENTIMENT_KEYWORD_FILE_START";
export const ADD_SENTIMENT_KEYWORD_FILE_FINISH = "ADD_SENTIMENT_KEYWORD_FILE_FINISH";
export const ADD_SENTIMENT_KEYWORD_FINISH = "ADD_SENTIMENT_KEYWORD_FINISH";
export const EDIT_SENTIMENT_KEYWORD_START = "EDIT_SENTIMENT_KEYWORD_START";
export const EDIT_SENTIMENT_KEYWORD_FINISH = "EDIT_SENTIMENT_KEYWORD_FINISH";
export const DELETE_SENTIMENT_KEYWORD_START = "DELETE_SENTIMENT_KEYWORD_START";
export const DELETE_SENTIMENT_KEYWORD_FINISH =
  "DELETE_SENTIMENT_KEYWORD_FINISH";
export const LIST_SENTIMENT_KEYWORDS_START = "LIST_SENTIMENT_KEYWORDS_START";
export const DELETE_MEDIA_ITEMS_START = "DELETE_MEDIA_ITEMS_START";
export const DELETE_MEDIA_ITEMS_FINISH = "DELETE_MEDIA_ITEMS_FINISH";
export const EDIT_MEDIA_SENTIMENT_START = "EDIT_MEDIA_SENTIMENT_START";
export const EDIT_MEDIA_SENTIMENT_FINISH = "EDIT_MEDIA_SENTIMENT_FINISH";

export const LIST_SENTIMENT_KEYWORDS_FINISH = "LIST_SENTIMENT_KEYWORDS_FINISH";

export const GET_TWITTER_HANDLES_START = "GET_TWITTER_HANDLES_START";
export const GET_TWITTER_HANDLES_FINISH = "GET_TWITTER_HANDLES_FINISH";

export const EDIT_TWITTER_HANDLES_START = "EDIT_TWITTER_HANDLES_START";
export const EDIT_TWITTER_HANDLES_FINISH = "EDIT_TWITTER_HANDLES_FINISH";

export const EDIT_INDIVIDUAL_SENTIMENT_KEYWORDS_START =
  "EDIT_INDIVIDUAL_SENTIMENT_KEYWORDS_START";
export const EDIT_INDIVIDUAL_SENTIMENT_KEYWORDS_FINISH =
  "EDIT_INDIVIDUAL_SENTIMENT_KEYWORDS_FINISH";
export const GET_INDIVIDUAL_SENTIMENT_KEYWORDS_START =
  "GET_INDIVIDUAL_EDIT_SENTIMENT_KEYWORDS_START";
export const GET_INDIVIDUAL_SENTIMENT_KEYWORDS_FINISH =
  "GET_INDIVIDUAL_EDIT_SENTIMENT_KEYWORDS_FINISH";

export const GET_YOUTUBE_USERS_START = "GET_YOUTUBE_USERS_START";
export const GET_YOUTUBE_USERS_FINISH = "GET_YOUTUBE_USERS_FINISH";

export const EDIT_YOUTUBE_USER_START = "EDIT_YOUTUBE_USER_START";
export const EDIT_YOUTUBE_USER_FINISH = "EDIT_YOUTUBE_USER_FINISH";

export const GET_ROLE_PERMISSIONS_START = "GET_ROLE_PERMISSIONS_START";
export const GET_ROLE_PERMISSIONS_FINISH = "GET_ROLE_PERMISSIONS_FINISH";

export const GET_YOUTUBE_VIDEOS_START = "GET_YOUTUBE_VIDEOS_START";
export const GET_YOUTUBE_VIDEOS_FINISH = "GET_YOUTUBE_VIDEOS_FINISH";

export const GET_YOUTUBE_CHANNELS_START = "GET_YOUTUBE_CHANNELS_START";
export const GET_YOUTUBE_CHANNELS_FINISH = "GET_YOUTUBE_CHANNELS_FINISH";

export const DELETE_YOUTUBE_CHANNEL_START = "DELETE_YOUTUBE_CHANNEL_START";
export const DELETE_YOUTUBE_CHANNEL_FINISH = "DELETE_YOUTUBE_CHANNEL_FINISH";

export const EDIT_YOUTUBE_CHANNEL_START = "EDIT_YOUTUBE_CHANNEL_START";
export const EDIT_YOUTUBE_CHANNEL_FINISH = "EDIT_YOUTUBE_CHANNEL_FINISH";

export const DELETE_YOUTUBE_VIDEO_START = "DELETE_YOUTUBE_VIDEO_START";
export const DELETE_YOUTUBE_VIDEO_FINISH = "DELETE_YOUTUBE_VIDEO_FINISH";

export const DELETE_YOUTUBE_COMMENT_START = "DELETE_YOUTUBE_COMMENT_START";
export const DELETE_YOUTUBE_COMMENT_FINISH = "DELETE_YOUTUBE_COMMENT_FINISH";

export const EDIT_YOUTUBE_VIDEO_START = "EDIT_YOUTUBE_VIDEO_START";
export const EDIT_YOUTUBE_VIDEO_FINISH = "EDIT_YOUTUBE_VIDEO_FINISH";

export const GET_SUPPORT_TICKETS_START = "GET_SUPPORT_TICKETS_START";
export const GET_SUPPORT_TICKETS_FINISH = "GET_SUPPORT_TICKETS_FINISH";
export const SOLVE_TICKET_START = "SOLVE_TICKET_START";
export const SOLVE_TICKET_FINISH = "SOLVE_TICKET_FINISH";

export const EDIT_TOPIC_NAME_START = "EDIT_TOPIC_NAME_START";
export const EDIT_TOPIC_NAME_FINISH = "EDIT_TOPIC_NAME_FINISH";

export const COMBGRAPH_DELETE_START = 'COMBGRAPH_DELETE_START';
export const COMBGRAPH_DELETE_FINISH = 'COMBGRAPH_DELETE_FINISH';

export const COMBGRAPH_GET_START = 'COMBGRAPH_GET_START'
export const COMBGRAPH_GET_FINISH = 'COMBGRAPH_GET_FINSIH'

export const COMBGRAPH_IDS_REMOVE_START = 'COMBGRAPH_IDS_REMOVE_START'
export const COMBGRAPH_IDS_REMOVE_FINISH = 'COMBGRAPH_IDS_REMOVE_FINISH'

export const DELETE_TWITTER_TWEET_START = 'DELETE_TWITTER_TWEET_START'
export const DELETE_TWITTER_TWEET_FINISH = 'DELETE_TWITTER_TWEET_FINISH'


// Product CRUD 

export const SAVE_PRODUCT = 'SAVE_PRODUCT'
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_FAIL = 'SAVE_PRODUCT_FAIL'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL= 'UPDATE_PRODUCT_FAIL'
export const CREATOR_SAVE_PRODUCT = "CREATOR_SAVE_PRODUCT"

// Product retrieving

export const GET_REQUEST_DATA = 'GET_REQUEST_DATA'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'

// Theme Props

export const THEME_MODE_TOGGLE = 'THEME_MODE_TOGGLE'
export const THEME_MODE_TOGGLE_SUCCESS = 'THEME_MODE_TOGGLE_SUCCESS'

// User Profile Ops

export const GET_USER_PROFILE_DATA = "GET_USER_PROFILE_DATA"
export const GET_USER_PROFILE_DATA_SUCCESS = "GET_USER_PROFILE_DATA_SUCCESS"

export const UPDATE_PROFILE_PRIMARY = "UPDATE_PROFILE_PRIMARY"
export const UPDATE_PROFILE_SECONDARY = "UPDATE_PROFILE_SECONDARY"

export const UPDATE_PROFILE_PRIMARY_SUCCESS = "UPDATE_PROFILE_PRIMARY_SUCCESS"
export const UPDATE_PROFILE_PRIMARY_FAILURE = "UPDATE_PROFILE_PRIMARY_FAILURE"


